"""Initial migration

Revision ID: 9025404525e9
Revises: 
Create Date: 2025-09-21 15:36:54.610733

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9025404525e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utilisateur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.Column('prenom', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('anciennete_permis', sa.Integer(), nullable=True),
    sa.Column('puissance', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.drop_table('simulation_clients')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulation_clients',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('prenom', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('telephone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type_utilisation', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('puissance_fiscale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('carburant', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('prime_estimee', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('date_simulation', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.CheckConstraint('age >= 18 AND age <= 100', name=op.f('simulation_clients_age_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('simulation_clients_pkey')),
    sa.UniqueConstraint('email', name=op.f('simulation_clients_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('utilisateur')
    # ### end Alembic commands ###
