"""Ajout de la colonne prime à la table utilisateur

Revision ID: ac150d09445c
Revises: 9025404525e9
Create Date: 2025-09-21 19:35:56.693831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac150d09445c'
down_revision = '9025404525e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prime', sa.Numeric(), nullable=True))
        batch_op.drop_column('primee')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primee', sa.NUMERIC(), autoincrement=False, nullable=True))
        batch_op.drop_column('prime')

    # ### end Alembic commands ###
